library(shiny)
library(demography)
library(latex2exp)
library(ggplot2)
ui <- bootstrapPage(
  titlePanel("Normal Distribution"),
  sliderInput("normal_mean",
              "miu",
              min = -20,
              max = 20,
              value= 0),
  sliderInput("normal_sd",
              "sigma",
              min = -10,
              max = 10,
              value= 1),
  plotOutput("normal_distribution"),
  
  titlePanel("t Distribution"),
  sliderInput("t_df",
              "df(degree of freedom)",
              min = 0,
              max = 20,
              value= 10),
  sliderInput("t_FakeSimulationNumber",
              "t-simulationNumber",
              min = 1000,
              max = 100000,
              value= 10000),
  sliderInput("t_breaks",
              "t hist-breaks",
              min = 0,
              max = 1,
              value= 0.5),
  plotOutput("t_distribution"),
  
  titlePanel("Chi-sqaured Distribution"),
  sliderInput("chisq_df",
              "df(degree of freedom)",
              min = 0,
              max = 20,
              value= 10),
  sliderInput("chisq_FakeSimulationNumber",
              "Chisq-SimulationNumber",
              min = 1000,
              max = 100000,
              value= 10000),
  sliderInput("chisq_breaks",
              "chisq hist-breaks",
              min = 0,
              max = 1,
              value= 0.5),
  plotOutput("chisq_distribution"),
  
  titlePanel("F Distribution Generated by Distribution"),
  sliderInput("m",
              "df 1",
              min = 0,
              max = 20,
              value= 3),
  sliderInput("n",
              "df 2",
              min = 0,
              max = 20,
              value= 10),
  sliderInput("f_FakeSimulationNumber",
              "F-SimulationNumber",
              min = 1000,
              max = 100000,
              value= 10000),
  sliderInput("f_breaks",
              "f hist-breaks",
              min = 0,
              max = 1,
              value= 0.5),
  textOutput("f"),
  plotOutput("f_distribution")
 
)


server <- function(input, output) {
  mean=0
  sd=1
  output$normal_distribution <- renderPlot({
    x <- rnorm(1000, input$normal_mean, input$normal_sd)
    plot(x = x, y = dnorm(x), xlab = "X", ylab = "PDF", 
         main = TeX(paste0("N(", input$normal_mean, ", ", input$normal_sd, "^2)")))
  })
  
  output$t_distribution <- renderPlot({
    dft=input$t_df
    nt=input$t_FakeSimulationNumber
    dataX <- rnorm(nt,mean=mean,sd=sd)
    dataTT <- rnorm(dft*nt,mean=mean,sd=sd)
    datamatrixT <-matrix(dataTT,nrow=dft,ncol=nt,byrow=TRUE,dimnames = NULL)
    datakafang <- sqrt(colSums(datamatrixT^2)/dft)
    datat <- dataX/datakafang
    xt=rt(nt,df=dft)
    yt=dt(xt,df=dft)
    hist(datat,freq=FALSE,breaks = seq(floor(min(datat)),ceiling(max(datat)),input$t_breaks),ylim=c(0,1),xlab = "X", ylab = "PDF", 
         main = TeX(paste0("t(", input$t_df, ")")))
    lines(xt,yt,type="p")
  })
  
  output$chisq_distribution <- renderPlot({
    mc=input$chisq_df
    nc=input$chisq_FakeSimulationNumber
    mean=0
    sd=1
    breakkf=input$chisq_breaks
    data <- rnorm(mc*nc,mean=mean,sd=sd)
    datamatrix <-matrix(data,nrow=mc,ncol=nc,byrow=TRUE,dimnames = NULL)
    data2 <-colSums(datamatrix^2)
    hist(data2,freq=FALSE,breaks = seq(floor(min(data2)),ceiling(max(data2)),breakkf),ylim=c(0,1),xlab="x",ylab="PDF",main = TeX(paste0("$χ^2_{", input$chisq_df, "}$")))
    xc=rchisq(nc,df=mc)
    yc=dchisq(xc,df=mc)
    lines(xc,yc,type="p")
  })
  output$f_distribution <- renderPlot({
    df1=input$m
    df2=input$n
    breakf=input$f_breaks
    nf=input$f_FakeSimulationNumber
    Sdata <- rnorm(nf*df1,mean=mean,sd=sd)
    Smatrix <- matrix(Sdata,nrow=df1,ncol=nf,byrow = TRUE,dimnames = NULL)
    SSdata <- colSums(Smatrix^2)/df1
    Xdata <- rnorm(nf*df2,mean=mean,sd=sd)
    Xmatrix <- matrix(Xdata,nrow=df2,ncol=nf,byrow = TRUE,dimnames = NULL)
    XXdata <- colSums(Xmatrix^2)/df2
    Fdata <- SSdata/XXdata
    hist(Fdata,freq=FALSE,breaks = seq(floor(min(Fdata)),ceiling(max(Fdata)),breakf),ylim=c(0,1), xlab = "X", ylab = "PDF", 
         main = TeX(paste0("$F_{", input$m, ",", input$n, "}(x)")))
    xf=rf(nf,df1=df1,df2=df2)
    yf=df(xf,df1=df1,df2=df2)
    lines(xf,yf,type="p")
  })
}
shinyApp(ui = ui, server = server)
