library(shiny)
library(demography)
library(latex2exp)
library(ggplot2)
ui <- bootstrapPage(
  titlePanel("Normal Distribution"),
    sliderInput("normal_mean",
                "μ",
                min = -20,
                max = 20,
                value= 0),
    sliderInput("normal_sd",
                "σ",
                min = -10,
                max = 10,
                value= 1),
  plotOutput("normal_distribution"),
  
  titlePanel("t Distribution"),
    sliderInput("t_df",
                "df(degree of freedom)",
                min = 0,
                max = 20,
                value= 5),
  plotOutput("t_distribution"),

  titlePanel("Chi-sqaured Distribution"),
  sliderInput("chisq_df",
              "df(degree of freedom)",
              min = 0,
              max = 20,
              value= 5),
  plotOutput("chisq_distribution"),
  
  titlePanel("F Distribution Generated by Distribution"),
  sliderInput("m",
              "df 1",
              min = 0,
              max = 20,
              value= 1),
  sliderInput("n",
              "df 2",
              min = 0,
              max = 20,
              value= 1),
  textOutput("f"),
  plotOutput("f_distribution"),
  
  titlePanel("Gamma Distribution"),
  sliderInput("shape",
              "shape",
              min = 0,
              max = 10,
              value= 1,
              step = 0.5),
  sliderInput("rate",
              "rate",
              min = 0,
              max = 5,
              value= 1,
              step = 0.5),
  plotOutput("gamma_distribution"),
  
  titlePanel("Beta Distribution"),
  sliderInput("shape1",
              "shape1",
              min = 0,
              max = 10,
              value= 5,
              step = 0.5),
  sliderInput("shape2",
              "shape2",
              min = 0,
              max = 5,
              value= 2,
              step = 0.5),
  plotOutput("beta_distribution")
)


server <- function(input, output) {
  
  output$normal_distribution <- renderPlot({
    x <- rnorm(1000, input$normal_mean, input$normal_sd)
    plot(x = x, y = dnorm(x), xlab = "X", ylab = "PDF", 
         main = TeX(paste0("N(", input$normal_mean, ", ", input$normal_sd, "^2)")))
  })
  
  output$t_distribution <- renderPlot({
    x <- rt(1000, df = input$t_df)
    plot(x = x, y = dt(x, df = input$t_df), xlab = "X", ylab = "PDF", 
         main = TeX(paste0("t(", input$df, ")")))
  })
  
  output$chisq_distribution <- renderPlot({
    x <- rchisq(1000, df = input$chisq_df)
    plot(x = x, y = dchisq(x, df = input$chisq_df),
         xlab = "X", ylab = "PDF", 
         main = TeX(paste0("$χ^2_{", input$chisq_df, "}$")))
  })
  

  
  
  output$f_distribution <- renderPlot({
    x <- rf(1000, input$m, input$n)
    plot(x = x, y = df(x, input$m, input$n), xlab = "X", ylab = "PDF", 
         main = TeX(paste0("$F_{", input$m, ",", input$n, "}(x)")))
  })
  
  output$gamma_distribution <- renderPlot({
    x <- rgamma(1000, input$shape, input$rate)
    plot(x = x, y = dgamma(x, input$shape, input$rate),
         xlab = "X", ylab = "PDF")
    })
  
  output$beta_distribution <- renderPlot({
    x <- rbeta(1000, input$shape1, input$shape2)
    plot(x = x, y = dbeta(x, input$shape1, input$shape2),
         xlab = "X", ylab = "PDF")
    })
  
  
}
shinyApp(ui = ui, server = server)
