(function($) {
    $(document).ready(function() {
	
	$('#conf_int').scianimator({
	    'images': ['conf_int/conf_int1.png', 'conf_int/conf_int2.png', 'conf_int/conf_int3.png', 'conf_int/conf_int4.png', 'conf_int/conf_int5.png', 'conf_int/conf_int6.png', 'conf_int/conf_int7.png', 'conf_int/conf_int8.png', 'conf_int/conf_int9.png', 'conf_int/conf_int10.png', 'conf_int/conf_int11.png', 'conf_int/conf_int12.png', 'conf_int/conf_int13.png', 'conf_int/conf_int14.png', 'conf_int/conf_int15.png', 'conf_int/conf_int16.png', 'conf_int/conf_int17.png', 'conf_int/conf_int18.png', 'conf_int/conf_int19.png', 'conf_int/conf_int20.png', 'conf_int/conf_int21.png', 'conf_int/conf_int22.png', 'conf_int/conf_int23.png', 'conf_int/conf_int24.png', 'conf_int/conf_int25.png', 'conf_int/conf_int26.png', 'conf_int/conf_int27.png', 'conf_int/conf_int28.png', 'conf_int/conf_int29.png', 'conf_int/conf_int30.png', 'conf_int/conf_int31.png', 'conf_int/conf_int32.png', 'conf_int/conf_int33.png', 'conf_int/conf_int34.png', 'conf_int/conf_int35.png', 'conf_int/conf_int36.png', 'conf_int/conf_int37.png', 'conf_int/conf_int38.png', 'conf_int/conf_int39.png', 'conf_int/conf_int40.png', 'conf_int/conf_int41.png', 'conf_int/conf_int42.png', 'conf_int/conf_int43.png', 'conf_int/conf_int44.png', 'conf_int/conf_int45.png', 'conf_int/conf_int46.png', 'conf_int/conf_int47.png', 'conf_int/conf_int48.png', 'conf_int/conf_int49.png', 'conf_int/conf_int50.png', 'conf_int/conf_int51.png', 'conf_int/conf_int52.png', 'conf_int/conf_int53.png', 'conf_int/conf_int54.png', 'conf_int/conf_int55.png', 'conf_int/conf_int56.png', 'conf_int/conf_int57.png', 'conf_int/conf_int58.png', 'conf_int/conf_int59.png', 'conf_int/conf_int60.png', 'conf_int/conf_int61.png', 'conf_int/conf_int62.png', 'conf_int/conf_int63.png', 'conf_int/conf_int64.png', 'conf_int/conf_int65.png', 'conf_int/conf_int66.png', 'conf_int/conf_int67.png', 'conf_int/conf_int68.png', 'conf_int/conf_int69.png', 'conf_int/conf_int70.png', 'conf_int/conf_int71.png', 'conf_int/conf_int72.png', 'conf_int/conf_int73.png', 'conf_int/conf_int74.png', 'conf_int/conf_int75.png', 'conf_int/conf_int76.png', 'conf_int/conf_int77.png', 'conf_int/conf_int78.png', 'conf_int/conf_int79.png', 'conf_int/conf_int80.png', 'conf_int/conf_int81.png', 'conf_int/conf_int82.png', 'conf_int/conf_int83.png', 'conf_int/conf_int84.png', 'conf_int/conf_int85.png', 'conf_int/conf_int86.png', 'conf_int/conf_int87.png', 'conf_int/conf_int88.png', 'conf_int/conf_int89.png', 'conf_int/conf_int90.png', 'conf_int/conf_int91.png', 'conf_int/conf_int92.png', 'conf_int/conf_int93.png', 'conf_int/conf_int94.png', 'conf_int/conf_int95.png', 'conf_int/conf_int96.png', 'conf_int/conf_int97.png', 'conf_int/conf_int98.png', 'conf_int/conf_int99.png', 'conf_int/conf_int100.png'],
	    'width': 480,
	    'delay': 100,
	    'loopMode': 'loop'
	});
	$('#conf_int').scianimator('play');
    });
})(jQuery);
